import pandas as pd
df = pd.read_csv("titanic.csv")
print("Missing Values:")
print(df.isnull().sum())
print("\nFirst 5 Rows:")
print(df.head())
print("\nDataset Information:")
print(df.info())
print("\nStatistical Summary:")
print(df.describe())
print("\nSurvival Count:")
print(df["Survived"].value_counts())
print("\nGender Count:")
print(df["Sex"].value_counts())